version: '3.3'

services:

  users-db:
    container_name: users-db
    build:
      context: ../ezasdf-users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  users-service:
    container_name: users-service
    build:
      context: ../ezasdf-users
      dockerfile: Dockerfile-dev
    volumes:
      - '../ezasdf-users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - FLASK_APP=ezasdf_users.py
    depends_on:
      - users-db
    links:
      - users-db